apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-flink-stateskew-15-atp
spec:
  benchmark: shuffle-flink
  load:
    loadType: "MessagesPerSecond"
    loadValues: [150000]
  resources:
    resourceType: "Instances"
    resourceValues: [9]
  slos:
    - name: throughput
  execution:
    metric: capacity
    strategy:
      name: "LinearSearch"
    duration: 300 # in seconds
    loadGenerationDelay: 60 # in seconds
    repetitions: 3
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "jobmanager-deployment.yaml"
        properties:
          container: "jobmanager"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "1000000"
    - patcher:
        type: "EnvVarPatcher"
        resource: "jobmanager-deployment.yaml"
        properties:
          container: "jobmanager"
          variableName: "MATCHER_ZIPF_TOTAL_SELECTIVITY"
      value: "1"
    - patcher:
        type: "EnvVarPatcher"
        resource: "jobmanager-deployment.yaml"
        properties:
          container: "jobmanager"
          variableName: "CONSUMER_STATE_SIZE_DISTRIBUTION"
      value: "zipf"
    - patcher:
        type: "EnvVarPatcher"
        resource: "jobmanager-deployment.yaml"
        properties:
          container: "jobmanager"
          variableName: "CONSUMER_STATE_SIZE_ZIPF_EXPONENT"
      value: "1.5"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "jobmanager-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "taskmanager-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
