apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-kstreams-recordsizevar-atp
spec:
  benchmark: shuffle-kstreams
  load:
    loadType: "MessagesPerSecond"
    loadValues: [175000]
  resources:
    resourceType: "Instances"
    resourceValues: [9]
  slos:
    - name: throughput
      properties: {}
  execution:
    metric: capacity
    strategy:
      name: "LinearSearch"
    duration: 300 # in seconds
    loadGenerationDelay: 60 # in seconds
    repetitions: 2
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "1000000"
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          container: "shuffle-load-generator"
          variableName: "RECORD_SIZE_DISTRIBUTION"
      value: "zipf"
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          container: "shuffle-load-generator"
          variableName: "RECORD_SIZE_ZIPF_EXPONENT"
      value: "1.5"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
