apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-flink-baseline-stp
spec:
  benchmark: shuffle-flink
  load:
    loadType: "MessagesPerSecond"
    # approx. 500k/sec -> [400k,600k]
    #loadValues: [100000, 102500, 105000, 107500, 110000, 112500, 115000, 117500, 120000, 122500, 125000, 127500, 130000, 132500, 135000, 137500, 140000, 142500, 145000, 147500, 150000]
    loadValues: [100000, 102500, 105000, 107500, 110000, 112500]
  resources:
    resourceType: "Instances"
    resourceValues: [9]
  slos:
    - name: lag trend
      properties:
        warmup: 180 # in seconds
  execution:
    metric: capacity
    strategy:
      name: "BinarySearch"
    duration: 900 # in seconds
    loadGenerationDelay: 30 # in seconds
    repetitions: 3
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "jobmanager-deployment.yaml"
        properties:
          container: "jobmanager"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "1000000"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "jobmanager-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "taskmanager-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
