apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-example-hzcast-atp
spec:
  benchmark: shuffle-hzcast
  load:
    loadType: "MessagesPerSecond"
    loadValues: [100000]
  resources:
    resourceType: "Instances"
    resourceValues: [3]
  slos:
    - name: throughput
  execution:
    metric: capacity
    strategy:
      name: "LinearSearch"
    duration: 600 # in seconds
    loadGenerationDelay: 30 # in seconds
    repetitions: 1
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-hzcast-deployment.yaml"
        properties:
          container: "shuffle-hzcast"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "1000000"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-hzcast-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
