apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-example-kstreams-atp
spec:
  benchmark: shuffle-kstreams
  load:
    loadType: "MessagesPerSecond"
    loadValues: [100000]
  resources:
    resourceType: "Instances"
    resourceValues: [3]
  slos:
    - name: throughput
      properties: {}
  execution:
    metric: capacity
    strategy:
      name: "LinearSearch"
    duration: 600 # in seconds
    loadGenerationDelay: 30 # in seconds
    repetitions: 1
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "1000000"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
