apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-example-spark-maxoffsets-atp
spec:
  benchmark: shuffle-spark
  load:
    loadType: "MaxOffsetsPerTrigger"
    loadValues: [1000]
  resources:
    resourceType: "Instances"
    resourceValues: [1]
  slos:
    - name: throughput
  execution:
    metric: capacity
    strategy:
      name: "FullSearch"
    duration: 600 # in seconds
    loadGenerationDelay: 30 # in seconds
    repetitions: 1
  configOverrides:
    - patcher:
        type: "ReplicaPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
      value: "1"
    - patcher:
        type: ResourceLimitPatcher
        resource: spark-worker-deployment.yaml
        properties:
          container: spark-worker
          limitedResource: cpu
      value: "250m"
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          container: "shuffle-load-generator"
          variableName: "NUM_RECORDS_PER_SOURCE_SECOND"
      value: "40000"
    - patcher:
        type: "EnvVarPatcher"
        resource: "spark-master-deployment.yaml"
        properties:
          container: "spark-submit"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "1000000"
