apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-spark-baseline-maxoffsets-atp
spec:
  benchmark: shuffle-spark
  load:
    loadType: "MaxOffsetsPerTrigger"
    loadValues: [10000, 100000, 1000000, 10000000, 100000000]
  resources:
    resourceType: "Instances"
    resourceValues: [9]
  slos:
    - name: throughput
      properties: {}
  execution:
    metric: capacity
    strategy:
      name: "FullSearch"
    duration: 900 # in seconds
    loadGenerationDelay: 30 # in seconds
    repetitions: 3
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          container: "shuffle-load-generator"
          variableName: "NUM_RECORDS_PER_SOURCE_SECOND"
      value: "250000"
    - patcher:
        type: "EnvVarPatcher"
        resource: "spark-master-deployment.yaml"
        properties:
          container: "spark-submit"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "1000000"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "spark-master-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "spark-worker-deployment.yaml"
        properties:
          variableName: "type"
      value: "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
